### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
see:

https://travis-ci.org/ramp-kits/titanic

for some reason it's not displayed on the PR

**Comment by aboucaud** [comment]
oups..

**Comment by agramfort** [comment]
travis is happy https://travis-ci.org/ramp-kits/titanic/builds/229704323

but for some reason does not update the PR status...

**Comment by agramfort** [comment]
good to go on my end !

**Comment by aboucaud** [comment]
the build passes on travis..
what do you expect on the PR except a green mark ?

**Comment by agramfort** [comment]
it should have a link to travis build log

**Comment by aboucaud** [comment]
hmmm I see

**Comment by agramfort** [comment]
maybe merge this PR and we'll see the next one

**Comment by agramfort** [comment]
we should put a link to the starting kit from the readme page

github will render the notebook nicely

**Comment by kegl** [comment]
I think it's solved with my reorg proposition. 

https://github.com/ramp-kits/titanic/pull/3

notebook will come up into the root dir

**Pull request merged**
